### ISSUE TITLE
NullPointerException from blossom.dual/slack?

### ISSUE THREAD

**Issue by rbelew** [ageneau/blossom#2]
hello Sylvain, just discovered and trying out your implementation of Blossom.  it looks very nice, thanks very much!
But while it passes your simple tests, it is failing on a small graph of mine:
```
g3
=>
#loom.graph.BasicEditableWeightedGraph{:nodeset #{0 7 1 4 6 3 2 5},
                                       :adj {0 {1 1, 2 1, 4 1, 5 1},
                                             1 {0 1, 2 1, 3 1},
                                             2 {0 1, 1 1, 4 1, 6 1, 7 1},
                                             3 {1 1},
                                             4 {5 1, 0 1, 2 1},
                                             5 {4 1, 7 1, 0 1},
                                             7 {5 1, 2 1},
                                             6 {2 1}}}

```

`(bmwm/max-weight-matching (loom/edges g3))`

Execution error (NullPointerException) at blossom.dual/eval23219$fn (dual.cljc:69).

any ideas why that might be?  regards, Rik

**Comment by ageneau** [comment]
Hello Rik.

The API expects a sequence of tuples [i j wt] but you're only passing [i j]. Try conjing 1 (default weight) to every element in your sequence. I tried your example and I'm getting the result: #{#{7 5} #{0 4} #{6 2} #{1 3}}.

Best,
Sylvain

**Comment by rbelew** [comment]
Indeed, (loom/edges) drops the edge weights!  thanks very much.
